fake_h2a_job = {'ETA case number': 'H-300-20119-524313', 'Company name': 'Lydianne Jurica', 'Trade Name/Doing Business As': None, 'Base salary': 13.62, 'Additional Wage Information': None, 'Begin date': '2020/10/16', 'End date': '2021/08/15', 'Company city': 'Broadus', 'Company state': 'MONTANA', 'Company zip code': '59317', 'Date posted': '2020/08/18', 'Experience Required': True, 'Job Order Link': 'https://seasonaljobs.dol.gov/job-order/H-300-20219-754673', 'Job Summary Link': 'https://seasonaljobs.dol.gov/jobs/H-300-20219-754673', 'Job duties': 'Farming', 'Job title': 'Livestock Handler', 'Months of Experience Required': 3, 'Multiple Worksites': False, 'Number of Workers Requested': None, 'Number of hours per week': 60, 'Special requirements': 'NONE', 'Telephone number to apply': '14066982115', 'Web address to apply': 'N/A', 'Worksite address': '310 West Powderville Rd', 'Worksite address city': 'Broadus', 'Worksite address state': 'MONTANA', 'Worksite address zip code': '59317', 'Employer Telephone number': '14066982115', 'e-mail to apply': 'theotherlydianne@yahoo.com', 'Section D': {'Housing Address': '307 West Powderville Rd', 'City': 'Broadus', 'State': 'Montana', 'Postal Code': '59317', 'County': 'Powder River', 'Housing Type': 'Fixed', 'Total Units': '1', 'Total Occupancy': '5'}, 'Section C': {'Address/Location': '310 West Powderville Rd', 'City': 'Broadus', 'State': 'Montana', 'Postal Code': '59317', 'County': 'Powder River'}, 'Section A': {'Workers Needed Total': '3', 'Workers Needed H-2A': '3'}, 'Number of Pages': 12
}

fake_h2a_job_2 = {'ETA case number': 'H-300-20114-511870', 'Company name': 'Lydianne Jurica', 'Trade Name/Doing Business As': None, 'Base salary': 13.62, 'Additional Wage Information': None, 'Begin date': '2020/10/16', 'End date': '2021/08/15', 'Company city': 'Broadus', 'Company state': 'MONTANA', 'Company zip code': '59317', 'Date posted': '2020/08/18', 'Experience Required': True, 'Job Order Link': 'https://seasonaljobs.dol.gov/job-order/H-300-20219-754673', 'Job Summary Link': 'https://seasonaljobs.dol.gov/jobs/H-300-20219-754673', 'Job duties': 'Farming', 'Job title': 'Livestock Handler', 'Months of Experience Required': 3, 'Multiple Worksites': False, 'Number of Workers Requested': None, 'Number of hours per week': 60, 'Special requirements': 'NONE', 'Telephone number to apply': '14066982115', 'Web address to apply': 'N/A', 'Worksite address': '310 West Powderville Rd', 'Worksite address city': 'Broadus', 'Worksite address state': 'MONTANA', 'Worksite address zip code': '59317', 'Employer Telephone number': '14066982115', 'e-mail to apply': 'theotherlydianne@yahoo.com', 'Section D': {'Housing Address': '307 West Powderville Rd', 'City': 'Broadus', 'State': 'Montana', 'Postal Code': '59317', 'County': 'Powder River', 'Housing Type': 'Fixed', 'Total Units': '1', 'Total Occupancy': '5'}, 'Section C': {'Address/Location': '310 West Powderville Rd', 'City': 'Broadus', 'State': 'Montana', 'Postal Code': '59317', 'County': 'Powder River'}, 'Section A': {'Workers Needed Total': '3', 'Workers Needed H-2A': '3'}, 'Number of Pages': 12
}

fake_h2b_job = {
'ETA case number': 'H-400-20187-695519', 'Company name': 'Bapptre Landscaping LLC', 'Trade Name/Doing Business As': 'Shine Illumination', 'Base salary': 17.57, 'Additional Wage Information': None, 'Begin date': '2020/10/01', 'End date': '2021/02/15', 'Company city': 'San Juan Capistrano', 'Company state': 'COLORADO', 'Company zip code': '92675', 'Date posted': '2020/08/18', 'Experience Required': False, 'Job Order Link': 'https://seasonaljobs.dol.gov/job-order/H-400-20187-695519', 'Job Summary Link': 'https://seasonaljobs.dol.gov/jobs/H-400-20187-695519', 'Job duties': 'Help a lot', 'Job title': 'Laborer Helpers', 'Months of Experience Required': 0, 'Multiple Worksites': True, 'Number of Workers Requested': 15, 'Number of hours per week': 40, 'Special requirements': 'Physical skills required: Must be able to stand, bend kneel and reach high areas to clean, move up and down stairs and regularly lift and/or move up to 50 pounds.  Ability to climb ladders and out onto tree branches, and string lights, wearing harnesses.  Electrical skills required include basic knowledge of electrical testing amperage and balancing power in circuits  \n\nSpecial requirements: Must be able to pass a ladder test.', 'Telephone number to apply': '+19493067280', 'Web address to apply': 'N/A', 'Worksite address': '32773 Calle Perfecto', 'Worksite address city': 'San Juan Capistrano', 'Worksite address state': 'CALIFORNIA', 'Worksite address zip code': '92675', 'Employer Telephone number': '+19493067280', 'e-mail to apply': 'bruce@shineillumination.com'
}

fake_h2a_inaccurate_job = {'ETA case number': 'H-300-20119-524313', 'Company name': 'Lydianne Jurica', 'Trade Name/Doing Business As': None, 'Base salary': 13.62, 'Additional Wage Information': None, 'Begin date': '2020/10/16', 'End date': '2021/08/15', 'Company city': 'Broadus', 'Company state': 'MONTANA', 'Company zip code': '59317', 'Date posted': '2020/08/18', 'Experience Required': True, 'Job Order Link': 'https://seasonaljobs.dol.gov/job-order/H-300-20219-754673', 'Job Summary Link': 'https://seasonaljobs.dol.gov/jobs/H-300-20219-754673', 'Job duties': 'Farming', 'Job title': 'Livestock Handler', 'Months of Experience Required': 3, 'Multiple Worksites': False, 'Number of Workers Requested': None, 'Number of hours per week': 60, 'Special requirements': 'NONE', 'Telephone number to apply': '14066982115', 'Web address to apply': 'N/A', 'Worksite address': 'bad', 'Worksite address city': 'not a city', 'Worksite address state': 'Antarctica', 'Worksite address zip code': '00000', 'Employer Telephone number': '14066982115', 'e-mail to apply': 'theotherlydianne@yahoo.com', 'Section D': {'Housing Address': 'not good', 'City': 'fake', 'State': 'North America', 'Postal Code': '59317', 'County': 'Canada', 'Housing Type': 'Fixed', 'Total Units': '1', 'Total Occupancy': '5'}, 'Section C': {'Address/Location': 'fake', 'City': 'Broadus', 'State': 'Europe', 'Postal Code': '11111', 'County': 'not real'}, 'Section A': {'Workers Needed Total': '3', 'Workers Needed H-2A': '3'}, 'Number of Pages': 12
}

fake_h2a_only_housing_inaccurate_job = {'ETA case number': 'H-300-20163-645163', 'Company name': 'Lydianne Jurica', 'Trade Name/Doing Business As': None, 'Base salary': 13.62, 'Additional Wage Information': None, 'Begin date': '2020/10/16', 'End date': '2021/08/15', 'Company city': 'Broadus', 'Company state': 'MONTANA', 'Company zip code': '59317', 'Date posted': '2020/08/18', 'Experience Required': True, 'Job Order Link': 'https://seasonaljobs.dol.gov/job-order/H-300-20219-754673', 'Job Summary Link': 'https://seasonaljobs.dol.gov/jobs/H-300-20219-754673', 'Job duties': 'Farming', 'Job title': 'Livestock Handler', 'Months of Experience Required': 3, 'Multiple Worksites': False, 'Number of Workers Requested': None, 'Number of hours per week': 60, 'Special requirements': 'NONE', 'Telephone number to apply': '14066982115', 'Web address to apply': 'N/A', 'Worksite address': '11 Cortlandt Manor Rd', 'Worksite address city': 'Katonah', 'Worksite address state': 'New York', 'Worksite address zip code': '10536', 'Employer Telephone number': '14066982115', 'e-mail to apply': 'theotherlydianne@yahoo.com', 'Section D': {'Housing Address': 'not good', 'City': 'fake', 'State': 'North America', 'Postal Code': '59317', 'County': 'Canada', 'Housing Type': 'Fixed', 'Total Units': '1', 'Total Occupancy': '5'}, 'Section C': {'Address/Location': 'fake', 'City': 'Broadus', 'State': 'Europe', 'Postal Code': '11111', 'County': 'not real'}, 'Section A': {'Workers Needed Total': '3', 'Workers Needed H-2A': '3'}, 'Number of Pages': 12
}

fake_h2a_only_worksite_inaccurate_job = {'ETA case number': 'H-300-20219-754673', 'Company name': 'Lydianne Jurica', 'Trade Name/Doing Business As': None, 'Base salary': 13.62, 'Additional Wage Information': None, 'Begin date': '2020/10/16', 'End date': '2021/08/15', 'Company city': 'Broadus', 'Company state': 'MONTANA', 'Company zip code': '59317', 'Date posted': '2020/08/18', 'Experience Required': True, 'Job Order Link': 'https://seasonaljobs.dol.gov/job-order/H-300-20219-754673', 'Job Summary Link': 'https://seasonaljobs.dol.gov/jobs/H-300-20219-754673', 'Job duties': 'Farming', 'Job title': 'Livestock Handler', 'Months of Experience Required': 3, 'Multiple Worksites': False, 'Number of Workers Requested': None, 'Number of hours per week': 60, 'Special requirements': 'NONE', 'Telephone number to apply': '14066982115', 'Web address to apply': 'N/A', 'Worksite address': 'not an address', 'Worksite address city': 'not a city', 'Worksite address state': 'Rainbow', 'Worksite address zip code': '59317', 'Employer Telephone number': '14066982115', 'e-mail to apply': 'theotherlydianne@yahoo.com', 'Section D': {'Housing Address': '307 West Powderville Rd', 'City': 'Broadus', 'State': 'Montana', 'Postal Code': '59317', 'County': 'Powder River', 'Housing Type': 'Fixed', 'Total Units': '1', 'Total Occupancy': '5'}, 'Section C': {'Address/Location': '310 West Powderville Rd', 'City': 'Broadus', 'State': 'Montana', 'Postal Code': '59317', 'County': 'Powder River'}, 'Section A': {'Workers Needed Total': '3', 'Workers Needed H-2A': '3'}, 'Number of Pages': 12
}


fake_h2b_inaccurate_job = {
'ETA case number': 'H-400-20187-695519', 'Company name': 'Bapptre Landscaping LLC', 'Trade Name/Doing Business As': 'Shine Illumination', 'Base salary': 17.57, 'Additional Wage Information': None, 'Begin date': '2020/10/01', 'End date': '2021/02/15', 'Company city': 'San Juan Capistrano', 'Company state': 'COLORADO', 'Company zip code': '92675', 'Date posted': '2020/08/18', 'Experience Required': False, 'Job Order Link': 'https://seasonaljobs.dol.gov/job-order/H-400-20187-695519', 'Job Summary Link': 'https://seasonaljobs.dol.gov/jobs/H-400-20187-695519', 'Job duties': 'Help a lot', 'Job title': 'Laborer Helpers', 'Months of Experience Required': 0, 'Multiple Worksites': True, 'Number of Workers Requested': 15, 'Number of hours per week': 40, 'Special requirements': 'Physical skills required: Must be able to stand, bend kneel and reach high areas to clean, move up and down stairs and regularly lift and/or move up to 50 pounds.  Ability to climb ladders and out onto tree branches, and string lights, wearing harnesses.  Electrical skills required include basic knowledge of electrical testing amperage and balancing power in circuits  \n\nSpecial requirements: Must be able to pass a ladder test.', 'Telephone number to apply': '+19493067280', 'Web address to apply': 'N/A', 'Worksite address': 'Rainbow', 'Worksite address city': 'Antarctica', 'Worksite address state': 'Sky Blue', 'Worksite address zip code': '99999', 'Employer Telephone number': '+19493067280', 'e-mail to apply': 'bruce@shineillumination.com'
}

all_fakes = [fake_h2a_job, fake_h2b_job, fake_h2a_inaccurate_job, fake_h2a_only_housing_inaccurate_job, fake_h2a_only_worksite_inaccurate_job, fake_h2b_inaccurate_job]
