# Dictionary of fields returned by Apify seasonal jobs scraper
apify_data_fields = {
    "Additional Wage Information": None,
    "Base salary": None,
    "Begin date": None,
    "Company city": None,
    "Company name": None,
    "Company state": None,
    "Company zip code": None,
    "Date posted": None,
    "ETA case number": None,
    "Employer Telephone number": None,
    "End date": None,
    "Experience Required": None,
    "Job Order Link": None,
    "Job Summary Link": None,
    "Job duties": None,
    "Job title": None,
    "Months of Experience Required": None,
    "Multiple Worksites": None,
    "Number of Pages": None,
    "Number of Workers Requested": None,
    "Number of hours per week": None,
    "Section A/Workers Needed H-2A": None,
    "Section A/Workers Needed Total": None,
    "Section C/Address/Location": None,
    "Section C/City": None,
    "Section C/County": None,
    "Section C/Postal Code": None,
    "Section C/State": None,
    "Section D/City": None,
    "Section D/County": None,
    "Section D/Housing Address": None,
    "Section D/Housing Type": None,
    "Section D/Postal Code": None,
    "Section D/State": None,
    "Section D/Total Occupancy": None,
    "Section D/Total Units": None,
    "Special requirements": None,
    "Telephone number to apply": None,
    "Trade Name/Doing Business As": None,
    "Web address to apply": None,
    "Worksite address": None,
    "Worksite address city": None,
    "Worksite address state": None,
    "Worksite address zip code": None,
    "e-mail to apply": None
}